spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML

  #数据库配置
  datasource:
    #JDBC配置
    username: root
    password: fp8oDILnjth8tN93P21ntgtjkY7Hdu//AS+ZVPe1gw90FRe4zjyXidZyYdUDA1G5Rq5O5LHfVhXbqqhtek6YsA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.233.28:3306/blog?useSSL=false&serverTimeZone=UTC&characterEncoding=utf-8
    #druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: config,stat,wall,slf4j
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      #数据库密码加密
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMCjBwKaNEiUeK3cEIehMB3VNNqo/oXLpNvagica8Dga8SOfVyZF83RX5/+4zDIgUBOF4elEkCN6k86pJ0JMKqECAwEAAQ==

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true

#  #redis配置
#  cache:
#    type: redis
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    #使用lettuce连接池
#    lettuce:
#      pool:
#        #最大连接数据库连接数,设 0 为没有限制
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#  data:
#    redis:
#      repositories:
#        enabled: false

server:
  port: 9090
#博客时间配置
blog:
  profile:
    initial-date: 2018-12-17
logging:
  path: /var/log/MyBlogSite
